version: "3"
services:

  django:
    build:
      context: justa/backend
    env_file:
      - .env
    volumes:
      - ./justa/backend:/justa
      - ./data:/mnt/data
    command: ["python", "manage.py", "runserver"]

  scrapy:
    build:
      context: justa/crawler
    links:
      - chrome
    env_file:
      - .env
    volumes:
      - ./justa/crawler:/justa
      - ./data:/mnt/data
    depends_on:
      - chrome
    command: ["scrapy", "crawl", "distrito_federal"]

  chrome:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
